### ISSUE TITLE
System.ArgumentException: Unable to sort because the IComparer.Compare()

### ISSUE THREAD

**Issue by wizche** [trailofbits/RpcInvestigator#28]
Howdy!

Amazing tool, thanks for sharing!
I got the following exception when adding/removing columns to an already filtered (on `IsServiceRunning` field) servers list.

```
System.ArgumentException: 'Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'System.Collections.Generic.ObjectComparer`1[BrightIdeasSoftware.ICluster]'.'
```
I couldn't reproduce it yet but I thought I report it anyway...

**Comment by wizche** [comment]
Actually I could reproduce:
1. Filter the servers list on `IsServiceRunning == True`
2. Add the `Procedures` column
3. Right-click on the `Procedures` column
4. Exception

**Comment by lilhoser** [comment]
Thanks @wizche I will take a look today. I am able to reproduce.

**Comment by lilhoser** [comment]
On the RPC servers tab, when the `Procedures` column is added to the listview via the column selector context menu, that column is displayed and populated with lists of raw NDR procedure objects for all of the RPC servers.  When the column is then right-clicked from the listview header, the listview control tries to sort the raw object lists into clusters in preparation for filtering.  However, the default `IComparer` algorithm cannot compare `IEnumerable` lists against each other, and an exception is thrown. Note that you can cause this exception by repeating the steps to reproducing this issue, but select another column like `Endpoints`.

The underlying issue here is that `Procedures` (and several other columns) are not meant to be selected and displayed in this listview, because it would be a horrible visual experience to try to deconstruct and display thousands of procedures in a tab meant to show meta information about the RPC server. This is why the column is hidden by default.  The intended way to navigate to procedures in RPCI is to either:

1. From the server list, double-click a server (which opens an endpoint tab containing exposed interfaces), then double-click an interface to show the procedures supported on that interface.
2. Navigate to `Library` -> `Procedures` to see all procedures for all RPC servers in the library and search from there.

However, it's apparent that neither is a great experience if you see an RPC server of interest and want to go straight to all procedures for that server.  So, I think there are two tasks for this issue:

- [ ] Remove unwanted columns (those that are not meant to be displayed and that would cause this exception) from the column selector
- [ ] Add an item in the row right-click context menu to "View all Procedures", which will open the Procedures tab filtered to all procedures for all interfaces owned by that RPC server.
